[package]
name = "indracore-availability-distribution"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.22"
tracing-futures = "0.2.4"
thiserror = "1.0.23"
parity-scale-codec = { version = "1.3.6", features = ["std"]  }

sp-core = { git = "https://github.com/selendra/substrate", branch = "master", features = ["std"]  }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "master" }

indracore-primitives = { path = "../../../primitives" }
indracore-erasure-coding = { path = "../../../erasure-coding" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-node-network-protocol = { path = "../../network/protocol" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }



[dev-dependencies]
assert_matches = "1.4.0"
maplit = "1.0"
indracore-subsystem-testhelpers = { package = "indracore-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "master", features = ["std"] }
sp-application-crypto = { git = "https://github.com/selendra/substrate", branch = "master" }
sp-keyring = { git = "https://github.com/selendra/substrate", branch = "master" }
sp-tracing = { git = "https://github.com/selendra/substrate", branch = "master" }
sc-keystore = { git = "https://github.com/selendra/substrate", branch = "master" }

