[package]
name = "indracore-runtime"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
bitvec = { version = "0.17.4", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
log = { version = "0.4.11", optional = true }
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.118", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
static_assertions = "1.1.0"
smallvec = "1.5.1"
hex-literal = { version = "0.3.1", optional = true }

sp-offchain = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-authority-discovery = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-consensus-babe = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-inherents = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-api = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-std = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-io = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-runtime = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-staking = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-core = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-session = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-version = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-transaction-pool = {  git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-block-builder = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }

frame-benchmarking = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false, optional = true }
frame-system-benchmarking = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false, optional = true }
frame-system = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
frame-support = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
frame-executive = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-authority-discovery = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-authorship = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-babe = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-balances = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-transaction-payment = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-collective = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-democracy = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-elections-phragmen = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-grandpa = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-identity = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-im-online = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-indices = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-membership = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-multisig = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-nicks = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-offences = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-proxy = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-scheduler = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-session = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-staking = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-staking-reward-curve = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
pallet-timestamp = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-treasury = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-vesting = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-utility = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-offences-benchmarking = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false, optional = true }
pallet-session-benchmarking = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false, optional = true }

runtime-common = { package = "indracore-runtime-common", path = "../common", default-features = false }
primitives = { package = "indracore-primitives", path = "../../primitives", default-features = false }

[build-dependencies]
substrate-wasm-builder = "3.0.0"

[features]
default = ["std"]
no_std = []
only-staking = []
std = [
    "log",
    "rustc-hex/std",
    "serde_derive",
	"serde/std",
    "bitvec/std",
    "parity-scale-codec/std",
    "sp-inherents/std",
	"sp-core/std",
	"sp-api/std",
	"sp-transaction-pool/std",
	"sp-block-builder/std",
	"sp-offchain/std",
	"sp-std/std",
    "sp-version/std",
	"sp-authority-discovery/std",
    "sp-consensus-babe/std",
	"sp-session/std",
    "sp-runtime/std",
	"sp-staking/std",
    "frame-support/std",
	"frame-executive/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"pallet-authority-discovery/std",
    "pallet-grandpa/std",
	"pallet-identity/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-nicks/std",
	"pallet-offences/std",
	"pallet-proxy/std",
    "pallet-authorship/std",
	"pallet-balances/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-collective/std",
	"pallet-elections-phragmen/std",
	"pallet-democracy/std",
    "pallet-scheduler/std",
	"pallet-session/std",
	"pallet-staking/std",
    "pallet-vesting/std",
	"pallet-utility/std",
    "pallet-timestamp/std",
	"pallet-treasury/std",
	"pallet-babe/std",
	"pallet-randomness-collective-flip/std",
	"primitives/std",
	"runtime-common/std",	
]
runtime-benchmarks = [
    "hex-literal",
    "sp-runtime/runtime-benchmarks",
	"runtime-common/runtime-benchmarks",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
    "frame-system-benchmarking",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-democracy/runtime-benchmarks",
	"pallet-elections-phragmen/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"pallet-offences-benchmarking",
	"pallet-session-benchmarking",
]