[workspace]
members = [
    "indracore",
	"core-primitives",
    "parachain",
    "primitives",
    "erasure-coding",
    "statement-table",
    "rpc",
    "xcm",
    "cli",
    "xcm/xcm-executor",
    "xcm/xcm-builder",
    "node/service",
    "node/primitives",
    "node/subsystem",
    "node/overseer",
    "node/subsystem-util",
    "node/collation-generation",
    "node/network/protocol",
    "node/network/statement-distribution",
    "node/network/bitfield-distribution",
    "node/network/availability-distribution",
    "node/network/collator-protocol",
    "node/network/pov-distribution",
    "node/network/bridge",
    "node/core/av-store",
    "node/core/backing",
    "node/core/bitfield-signing",
    "node/core/candidate-selection",
    "node/core/candidate-validation",
    "node/core/chain-api",
    "node/core/proposer",
    "node/core/runtime-api",
    "node/core/provisioner",
    "runtime/common",
    "runtime/parachains",
    "runtime/indracore",
]

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
# Indracore runtime requires unwinding.
panic = "unwind"