[workspace]
members = [
	"core-primitives",
    "parachain",
    "primitives",
    "rpc",
    "xcm",
    "xcm/xcm-executor",
    "xcm/xcm-builder",
    "runtime/common",
    "runtime/parachains",
    "runtime/indracore",
    
]

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
# Indracore runtime requires unwinding.
panic = "unwind"