version: "3.1"
services:
  indracore:
    image: indracore
    container_name: "indracore-node"
    restart: always
    ports:
      - 30333:30333
      - 9933:9933 
      - 9944:9944
    volumes:
      - ./:/home/indracore
    working_dir: /home/indracore
    # command: sh -c "./home/indracore/target/release/indracore --rpc-cors "*" --pruning archive"
    command: sh -c "./target/release/indracore"
