version: "3.1"
services:
  indracore:
    image: phusion/baseimage
    container_name: "indracore-node"
    restart: always
    ports:
      - 30333:30333
      - 9933:9933 
      - 9944:9944
    volumes:
      - ./:/home/indracore
    working_dir: /home/indracore
    command: >
    sh -c "cargo build --release && ./target/release/indracore --rpc-cors "*" --pruning archive"