[package]
name = "indracore-node-primitives"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Primitives types for the Node-side"

[dependencies]
futures = "0.3.12"
schnorrkel = "0.9.1"
thiserror = "1.0.22" 
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }

sp-runtime = { git = "https://github.com/selendra/substrate", branch = "master", default-features = false }
sp-core = { git = "https://github.com/selendra/substrate", branch = "master" }
sp-consensus-vrf = { git = "https://github.com/selendra/substrate", branch = "master" }
sp-consensus-slots = { git = "https://github.com/selendra/substrate", branch = "master", default-features = false }
sp-application-crypto = { git = "https://github.com/selendra/substrate", branch = "master" }
sp-consensus-babe = { git = "https://github.com/selendra/substrate", branch = "master" }

indracore-primitives = { path = "../../primitives" }
indracore-statement-table = { path = "../../statement-table" }

