[package]
name = "indracore-rpc"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "1.3.5", default-features = false }
jsonrpc-core = "15.1.0"

sp-blockchain = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sp-runtime = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sp-api = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sp-consensus = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sp-consensus-babe = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sp-transaction-pool = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sp-block-builder = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }

sc-client-api = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sc-chain-spec = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sc-rpc = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sc-consensus-babe = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sc-consensus-babe-rpc = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sc-consensus-epochs = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sc-finality-grandpa = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sc-finality-grandpa-rpc = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sc-keystore = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sc-sync-state-rpc = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }

substrate-frame-rpc-system = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
pallet-transaction-payment-rpc = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }

indracore-primitives = { package = "indracore-primitives", path = "../primitives" }