[package]
name = "indracore-node-subsystem-test-helpers"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Subsystem traits and message definitions"

[dependencies]
smallvec = "1.6.1"
async-trait = "0.1.42"
futures = "0.3.12"
futures-timer = "3.0.2"
tracing = "0.1.22"
tracing-futures = "0.2.4"
parking_lot = "0.11.1"
pin-project = "1.0.4"
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }

sc-network = { git = "https://github.com/selendra/substrate", branch = "master" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "master" }

indracore-node-primitives = { path = "../primitives" }
indracore-node-subsystem = { path = "../subsystem" }
indracore-node-subsystem-util = { path = "../subsystem-util" }
indracore-primitives = { path = "../../primitives" }
indracore-statement-table = { path = "../../statement-table" }

[dev-dependencies]
indracore-overseer = { path = "../overseer" }
