[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://selendra.org"
repository = "https://github.com/selendra/indracore"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.0.0"
jsonrpc-pubsub = "15.0.0"
futures = "0.3.1"

node-primitives = { version = "2.0.0", path = "../primitives" }
node-indracore-runtime = { version = "2.0.0", path = "../runtime" }
pallet-contracts-rpc = { version = "0.8.0", path = "../../frame/contracts/rpc/" }
pallet-transaction-payment-rpc = { version = "2.0.0", path = "../../frame/transaction-payment/rpc/" }
sc-client-api = { version = "2.0.0", path = "../../client/api" }
sc-consensus-babe = { version = "0.8.0", path = "../../client/consensus/babe" }
sc-consensus-babe-rpc = { version = "0.8.0", path = "../../client/consensus/babe/rpc" }
sc-consensus-epochs = { version = "0.8.0", path = "../../client/consensus/epochs" }
sc-finality-grandpa = { version = "0.8.0", path = "../../client/finality-grandpa" }
sc-finality-grandpa-rpc = { version = "0.8.0", path = "../../client/finality-grandpa/rpc" }
sc-keystore = { version = "2.0.0", path = "../../client/keystore" }
sc-rpc-api = { version = "0.8.0", path = "../../client/rpc-api" }
sc-rpc = { version = "2.0.0", path = "../../client/rpc" }
sc-network = { version = "0.8.0", path = "../../client/network" }
sp-api = { version = "2.0.0", path = "../../primitives/api" }
sp-block-builder = { version = "2.0.0", path = "../../primitives/block-builder" }
sp-blockchain = { version = "2.0.0", path = "../../primitives/blockchain" }
sp-consensus = { version = "0.8.0", path = "../../primitives/consensus/common" }
sp-consensus-babe = { version = "0.8.0", path = "../../primitives/consensus/babe" }
sp-runtime = { version = "2.0.0", path = "../../primitives/runtime" }
sp-transaction-pool = { version = "2.0.0", path = "../../primitives/transaction-pool" }
substrate-frame-rpc-system = { version = "2.0.0", path = "../../utils/frame/rpc/system" }

ethereum = { version = "0.1.0", package = "pallet-ethereum", path = "../../frame/ethereum" }
frontier-rpc = { path = "../../frontier/rpc" }
frontier-rpc-primitives = { path = "../../frontier/rpc/primitives" }
