[package]
name = "indracore-runtime-common"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.123", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
static_assertions = "1.1.0"

sp-std = { package = "sp-std", git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-runtime = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-staking = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }

frame-support = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
frame-system = {git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
frame-benchmarking = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false, optional = true }
pallet-timestamp = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-transaction-payment = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-treasury = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-staking = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-authorship = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-balances = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
pallet-session = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }

primitives = { package = "indracore-primitives", path = "../../primitives", default-features = false }

[features]
default = ["std"]
no_std = []
std = [
	"parity-scale-codec/std",
	"serde_derive",
	"serde/std",
	"sp-std/std",
    "sp-runtime/std",
	"frame-support/std",
    "frame-system/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-staking/std",
	"pallet-timestamp/std",
	"pallet-treasury/std",
	"pallet-transaction-payment/std",
	"pallet-session/std",
    "primitives/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
