[package]
name = "indracore-node-subsystem-util"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Subsystem traits and message definitions"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.8"
futures-timer = "3.0.2"
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
parking_lot = { version = "0.11.1", optional = true }
pin-project = "1.0.2"
streamunordered = "0.5.1"
thiserror = "1.0.22"
tracing = "0.1.22"
tracing-futures = "0.2.4"

sc-network = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sp-core = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sp-application-crypto = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
sp-keystore = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
substrate-prometheus-endpoint = { git = "https://github.com/selendra/substrate", branch = "v2.0.1" }

indracore-node-primitives = { path = "../primitives" }
indracore-node-subsystem = { path = "../subsystem" }
indracore-primitives = { path = "../../primitives" }