[package]
name = "indracore-collator-protocol"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"
thiserror = "1.0.22"

indracore-primitives = { path = "../../../primitives" }
indracore-node-network-protocol = { path = "../../network/protocol" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }