[package]
name = "indracore-node-core-av-store"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
futures-timer = "3.0.2"
kvdb = "0.7.0"
kvdb-rocksdb = "0.9.1"
thiserror = "1.0.22"
tracing = "0.1.22"
tracing-futures = "0.2.4"

parity-scale-codec = { version = "1.3.5", features = ["derive"] }
erasure = { package = "indracore-erasure-coding", path = "../../../erasure-coding" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-node-subsystem-util = { path = "../../subsystem-util" }
indracore-overseer = { path = "../../overseer" }
indracore-primitives = { path = "../../../primitives" }

sc-service = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
