[package]
name = "indracore-node-core-approval-voting"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
bitvec = "0.20.1"
futures = "0.3.8"
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["bit-vec", "derive"] }

sc-client-api = { git = "https://github.com/selendra/substrate", branch = "master", default-features = false }
sp-consensus-slots = { git = "https://github.com/selendra/substrate", branch = "master", default-features = false }
sp-blockchain = { git = "https://github.com/selendra/substrate", branch = "master", default-features = false }

indracore-subsystem = { package = "indracore-node-subsystem", path = "../../subsystem" }
indracore-overseer = { path = "../../overseer" }
indracore-primitives = { path = "../../../primitives" }
indracore-node-primitives = { path = "../../primitives" }

[dev-dependencies]