[package]
name = "indracore-overseer"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"
futures-timer = "3.0.2"
streamunordered = "0.5.1"
indracore-primitives = { path = "../../primitives" }
client = { package = "sc-client-api", git = "https://github.com/selendra/substrate", branch = "v2.0.1" }
indracore-subsystem = { package = "indracore-node-subsystem", path = "../subsystem" }
indracore-node-subsystem-util = { path = "../subsystem-util" }
indracore-node-primitives = { package = "indracore-node-primitives", path = "../primitives" }
async-trait = "0.1.42"