[package]
name = "precompiles"
version = "0.1.0"
authors = ["Selendra"]
edition = "2018"

[dependencies]
log = "0.4.8"
rustc-hex = { version = "2.0.1", default-features = false }
ripemd160 = { version = "0.9", default-features = false }

sp-std = { version = "2.0.0", path = "../../../primitives/std" , default-features = false}
sp-core = { version = "2.0.0", path = "../../../primitives/core", default-features = false }
pallet-evm = { version = "2.0.0", path = "../../../frame/evm", default-features = false}

[features]
default = [ "std" ]
std = [
	"sp-std/std",
	"sp-core/std",
	"ripemd160/std",
]
